"""Move number to apartment

Revision ID: 6d417e615d0d
Revises: 85cfda67962f
Create Date: 2025-12-17 18:38:41.963619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d417e615d0d"
down_revision: Union[str, Sequence[str], None] = "85cfda67962f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("announcements", "apartment_number")
    op.add_column("apartments", sa.Column("number", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apartments", "number")
    op.add_column(
        "announcements",
        sa.Column(
            "apartment_number", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
