"""Add agent contacts table

Revision ID: 85cfda67962f
Revises: 28a0bfba68a5
Create Date: 2025-12-16 21:09:47.898593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85cfda67962f"
down_revision: Union[str, Sequence[str], None] = "28a0bfba68a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("agent_contacts_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_contacts_pkey")),
        sa.UniqueConstraint("user_id", name=op.f("agent_contacts_user_id_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_contacts")
    # ### end Alembic commands ###
