"""add_secondary_market_and_requests

Revision ID: aa236488ff8a
Revises: 3e076fde4dc8
Create Date: 2025-12-23 12:25:28.578344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa236488ff8a"
down_revision: Union[str, Sequence[str], None] = "3e076fde4dc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chessboard_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("announcement_id", sa.Integer(), nullable=False),
        sa.Column("target_house_id", sa.Integer(), nullable=False),
        sa.Column("target_section_id", sa.Integer(), nullable=False),
        sa.Column("target_floor_id", sa.Integer(), nullable=False),
        sa.Column("target_apartment_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="requeststatus"),
            nullable=False,
        ),
        sa.Column("developer_comment", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["announcements.id"],
            name=op.f("chessboard_requests_announcement_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["target_floor_id"],
            ["floors.id"],
            name=op.f("chessboard_requests_target_floor_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["target_house_id"],
            ["houses.id"],
            name=op.f("chessboard_requests_target_house_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["target_section_id"],
            ["sections.id"],
            name=op.f("chessboard_requests_target_section_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chessboard_requests_pkey")),
    )
    op.add_column(
        "announcements", sa.Column("floor_number", sa.Integer(), nullable=True)
    )
    op.add_column(
        "announcements", sa.Column("total_floors", sa.Integer(), nullable=True)
    )
    op.add_column(
        "announcements", sa.Column("apartment_number", sa.String(), nullable=True)
    )
    op.alter_column(
        "announcements", "apartment_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column("houses", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("houses_owner_id_fkey"), "houses", "users", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("houses_owner_id_fkey"), "houses", type_="foreignkey")
    op.drop_column("houses", "owner_id")
    op.alter_column(
        "announcements", "apartment_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("announcements", "apartment_number")
    op.drop_column("announcements", "total_floors")
    op.drop_column("announcements", "floor_number")
    op.drop_table("chessboard_requests")
    # ### end Alembic commands ###
