"""add_cascade_delete_users

Revision ID: afa04416fb3e
Revises: 23274f0ef27c
Create Date: 2025-12-25 14:00:02.716443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afa04416fb3e"
down_revision: Union[str, Sequence[str], None] = "23274f0ef27c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "announcements",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=14, scale=2),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("announcements_user_id_fkey"), "announcements", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("announcements_user_id_fkey"),
        "announcements",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("announcements_user_id_fkey"), "announcements", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("announcements_user_id_fkey"),
        "announcements",
        "users",
        ["user_id"],
        ["id"],
    )
    op.alter_column(
        "announcements",
        "price",
        existing_type=sa.Numeric(precision=14, scale=2),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
